#!/bin/sh

[ $ACTION = "ifup" ] || exit 0

if [ $INTERFACE = "wan" ]; then
	awk '{printf "%d\n", $1}' /proc/uptime >> /tmp/easyconfig_wan_up

	sleep 5

	VPNS=$(uci show network | awk -F. '/trigger='\''wan'\''$/{print $2}')
	if [ -n "$VPNS" ]; then
		for VPN in $VPNS; do
			if [ "x$(uci -q get network.$VPN.auto)" = "x0" ]; then
				ifup $VPN
			fi
		done
	fi

	if [ -e /etc/config/openvpn ]; then
		OVPNS=$(uci -q show openvpn | awk -F. '/trigger='\''wan'\''$/{print $2}')
		if [ -n "$OVPNS" ]; then
			for OVPN in $OVPNS; do
				uci set openvpn.$OVPN.enabled=1
			done
			/etc/init.d/openvpn restart
			uci revert openvpn
		fi
	fi

	if [ -e /etc/config/zerotier ]; then
		ZT=$(uci -q get zerotier.global.trigger)
		if [ "x$ZT" = "xwan" ]; then
			uci set zerotier.global.enabled=1
			/etc/init.d/zerotier restart
			uci revert zerotier
		fi
	fi
fi

exit 0
